#!/bin/bash

set -euo pipefail

. "scripts/github/common.sh"

install_go
build_meta

tools/meta/meta resolve-versions --mpd "${MPD_VERSION}" --libmpdclient "${LIBMPDCLIENT_VERSION}" >> "${GITHUB_OUTPUT}"
