#!/usr/bin/env bash

function files_to_format() {
    if test "$#" -gt 0; then
        printf "%s\n" "$@"
    else
        git ls-files | egrep '\.(c|h)$'
    fi
}

files_to_format "$@" | while read F; do
    clang-format -i $F
done
