#!/usr/bin/env bash

src_files() {
    if test "$#" -gt 0; then
        printf "%s\n" "$@"
    else
        git ls-files
    fi
}

src_files "$@" | while read F; do
    case $F in
        *.cc|*.c|*.h)
            clang-format -i "$F"
            ;;
        *.go)
            gofmt -w "$F"
            ;;
    esac
done
