#!/bin/bash
die() {
    echo "$@" >&2
    exit 1
}

run_id="$(head -c 100 /dev/urandom | sha256sum | head -c 30)"

tagname="test/ashuffle:run_${run_id}"

tty="-t"
build_extra=()
run_extra=()
nobuild="false"

while test $# -gt 0; do
    case "$1" in
        --no_tty)
            tty=""
            ;;
        --no_build_use_image=*)
            nobuild="true"
            tagname="${1#"--no_build_use_image="}"
            ;;
        --build.*)
            build_extra+=( "--${1#"--build."}" )
            ;;
        --build_bare.*)
            build_extra+=( "${1#"--build_bare."}" )
            ;;
        *)
            run_extra+=( "$1" )
            ;;
    esac
    shift
done

if [[ "${nobuild}" != "true" ]]; then
    ./scripts/build-test-image \
        --image-tag "${tagname}" \
        "${build_extra[@]}" || die "couldn't build test image"
fi

exec docker run \
    --name "ashuffle_integration_run_${run_id}" \
    --privileged \
    --device /dev/fuse:/dev/fuse \
    --rm \
    $tty \
    -i \
    "${tagname}" \
    "${run_extra[@]}"
